---
# Homepage configuration
# See https://fontawesome.com/icons for icons options

title: "Shared Homepage"
subtitle: "Dura IT Ops"
logo: "assets/duralogo.png"
# icon: "fas fa-skull-crossbones"

# Optional message
# See https://bulma.io/documentation/components/message/#colors for styling options.
#message:
  #style: "is-warning"
  #title: "Hi there!"
  #content: "Welcome to the new IT OPS Dashboard! Please let Jason know if anything needs changing."

# Optional navbar
links:
  - name: "Dura"
    icon: "fas fa-home"
    url: "https://jstewds.github.io/"
  - name: "Bertch"
    icon: "fas fa-road"
    url: "https://jstewds.github.io/bertch/"
  - name: "Office 365"
    icon: "fas fa-cogs"
    url: "https://jstewds.github.io/o365/"
  - name: "Azure AD (AAD)"
    icon: "fas fa-book"
    url: "https://portal.azure.com/#home"
  - name: "DuraLINK"
    icon: "fas fa-link"
    url: "https://duralink.durasupreme.com"

# Services
# First level array represent a group.
# Leave only a "items" key if not using group (group name, icon & tagstyle are optional, section separation will not be displayed).
services:
  - name: "Office 365"
    icon: "fas fa-cogs"
    items:
      - name: "Office Admin Page"
        logo: "/assets/tools/o365.png"
        subtitle: "Access the Main Office 365 Admin Page"
        tag: "Admin? More like Sadmin..."
        url: "https://admin.microsoft.com/AdminPortal/Home#/homepage"
      - name: "Exchange Admin Center"
        logo: "/assets/tools/exchange.png"
        subtitle: "Direct Access to the Exchange Admin Center"
        tag: "Which witch is which?"
        url: "https://outlook.office365.com/ecp/?rfr=Admin_o365&exsvurl=1&mkt=en-US&Realm=durasupreme.com"
      - name: "Sharepoint Admin Center"
        logo: "/assets/tools/sharepoint.png"
        subtitle: "Direct Access to the Sharepoint Admin Center"
        tag: "Sharing is caring"
        url: "https://durasupremeinc-admin.sharepoint.com/_layouts/15/online/AdminHome.aspx#/home"
      - name: "Security - Threat Review"
        logo: "/assets/tools/sharepoint.png"
        subtitle: "Direct Access to Security Center - Threat Review"
        tag: "Who goes there?"
        url: "https://security.microsoft.com/threatreview"