---
# Homepage configuration
# See https://fontawesome.com/icons for icons options

title: "Shared Homepage"
subtitle: "Dura IT Ops"
logo: "assets/duralogo.png"
# icon: "fas fa-skull-crossbones"

Columns: "4"

# Optional message
# See https://bulma.io/documentation/components/message/#colors for styling options.
#message:
  #style: "is-warning"
  #title: "Hi there!"
  #content: "Welcome to the new IT OPS Dashboard! Please let Jason know if anything needs changing."

# Optional navbar
links:
  - name: "Dura"
    icon: "fas fa-home"
    url: "https://jstewds.github.io/"
  - name: "Bertch"
    icon: "fas fa-road"
    url: "https://jstewds.github.io/bertch/"
  - name: "Office 365"
    icon: "fas fa-cogs"
    url: "https://jstewds.github.io/o365/"
  - name: "Azure AD (AAD)"
    icon: "fas fa-book"
    url: "https://portal.azure.com/#home"
  - name: "DuraLINK"
    icon: "fas fa-link"
    url: "https://duralink.durasupreme.com"

# Services
# First level array represent a group.
# Leave only a "items" key if not using group (group name, icon & tagstyle are optional, section separation will not be displayed).
services:
  - name: "Monitoring"
    icon: "fas fa-heartbeat"
    items:
      - name: "PRTG"
        logo: "/assets/tools/PRTG.png"
        subtitle: "Network and Server Monitor"
        tag: "Wacky Germans!"
        url: "https://#"
      - name: "NetDisco"
        logo: "/assets/tools/disco.jpg"
        subtitle: "Network stats and config changes"
        tag: "Boogie Wonderland!"
        url: "http://10.1.1.90:5000/"
      - name: "LANSweeper"
        logo: "/assets/tools/lansweeper.png"
        subtitle: "Workstation and Server Inventory Tool"
        tag: "BringOnTheBroom"
        url: "http://server48.bcm.local:81/"
  - name: "SaaS Apps"
    icon: "fas fa-cloud-upload-alt"
    items:
      - name: "IT Glue"
        logo: "/assets/tools/itglue.png"
        subtitle: "Documentation"
        tag: "TastesGreat"
        url: "https://durasupreme.itglue.com/4922755"
      - name: "CrowdStrike"
        logo: "/assets/tools/crowdstrike.png"
        subtitle: "Security Software"
        tag: "I was saying boo-urns!"
        url: "https://falcon.crowdstrike.com"  
      - name: "Barracuda"
        logo: "/assets/tools/barracuda.png"
        subtitle: "Email Protection & ATP "
        tag: "And tales, it never fails"
        url: "https://ess.barracudanetworks.com/"  
  - name: "Everything Else"
    icon: "fas fa-ball-pile"
    items:
      - name: "Website"
        logo: "/assets/tools/bertch.png"
        subtitle: "Their public website"
        # tag: "Wacky Germans!"
        url: "https://www.bertch.com/"
